#!/bin/sh
set -e
package_name=fsearch-first-configuration
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/fsearch"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/fsearch"
;;
esac
exit 0
